<?php

namespace AppBundle\Repository;

/**
 * courseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class courseRepository extends \Doctrine\ORM\EntityRepository
{

    public function testQuery(){
        /*
         * createQueryBuilder : constructeur de requêtes
         *      definir l'alias de l'entité
         * methodes reprennant le nom des commandes SQL
         *      SELECT : choix des propriétés de l'entité en utilisant l'alias
         *               renvvoi un array de array
         *      where / andwhere / orWhere
         *              utilisation de where en première condition
         *              a partir de la deuxième condition : utilisation de andWhere ou orWhere
         *              utilisation des paramètres de requète PDO
         *
         *
         * getQuery : exécution de la requète / appel de cette méthode en avant dernière position
         * recuperration des résultats : dernière position
         *      getResult : renvoie un array d'objet
         */
        $query = $this ->createQueryBuilder('CoursesAlias')
            ->select('CoursesAlias.course, CoursesAlias.slug')
            ->where ('CoursesAlias.course = :nameParam')
            ->andWhere('coursesAlias.course LIKE :likeParam')
            ->setParameters([
                'nameParam'=>'web designer',
                'likeParam'=>'%design%'
            ])
            ->getQuery()
            ->getResult()
        ;

        //reqete de regroupement
        $query = this->createQueryBuilder('courseAlias')
            ->getQuery()
            ->getresult();

        return $query;
    }
}
